-- Players are anonymous: a random token (stored only as a SHA-256 hash) and a
-- display name built from the safe pet-name list. No personal data.
CREATE TABLE players (
    id              VARCHAR(36)  PRIMARY KEY,
    token_hash      VARCHAR(64)  NOT NULL UNIQUE,
    display_name    VARCHAR(40)  NOT NULL,
    created_at_ms   BIGINT       NOT NULL
);

-- Every verified run. The server computed finish_micros itself by replaying
-- log (the client never reports a time).
CREATE TABLE runs (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id       VARCHAR(36)  NOT NULL REFERENCES players (id),
    track_id        VARCHAR(40)  NOT NULL,
    finish_micros   BIGINT       NOT NULL,
    log             TEXT         NOT NULL,
    sim_version     INT          NOT NULL,
    created_at_ms   BIGINT       NOT NULL
);

CREATE INDEX runs_track_time ON runs (track_id, created_at_ms, finish_micros);
CREATE INDEX runs_player_track ON runs (player_id, track_id, finish_micros);
